Create table roupa

(
    codigo INT generated by default as identity primary key,
    nome varchar(45) not null,
	descricao varchar(100),
	tamanho varchar(10) not null,
	tipo varchar(20) not null,
	preco decimal (6,2) not null,
	disponivel boolean default true not null,
	foto bytea,
	codigoUsuario int not null,
	codigoVenda int
);


Create table usuario

(
    codigo INT generated by default as identity primary key,
    email varchar(45) unique not null,
	senha varchar(45) not null,
	nome varchar(50) not null,
	dataNasc date not null,
	telefone char(11) not null,
	chavePix varchar(50)

);


Create table venda

(
    codigo INT generated by default as identity primary key,
    horario timestamp not null default CURRENT_TIMESTAMP,
	codigoUsuario int not null,
	codigoEndereco int not null
);


Create table endereco

(
    codigo INT generated by default as identity primary key,
    bairro varchar(30) not null,
	numero int,
	cidade varchar(30) not null,
	estado char (2) not null,
	codigoUsuario int not null
);

ALTER TABLE endereco
ADD CONSTRAINT fk_usuario FOREIGN KEY (codigoUsuario)
REFERENCES usuario(codigo); 

ALTER TABLE venda
ADD CONSTRAINT fk_usuario FOREIGN KEY (codigoUsuario)
REFERENCES usuario(codigo); 

ALTER TABLE venda
ADD CONSTRAINT fk_endereco FOREIGN KEY (codigoEndereco)
REFERENCES endereco(codigo);

ALTER TABLE roupa
ADD CONSTRAINT fk_usuario FOREIGN KEY (codigoUsuario)
REFERENCES usuario(codigo); 

ALTER TABLE roupa
ADD CONSTRAINT fk_venda FOREIGN KEY (codigoVenda)
REFERENCES venda(codigo);

ALTER TABLE venda
ADD mensagem VARCHAR(50);

INSERT INTO usuario (email, senha, nome, dataNasc, telefone, chavePix) 
VALUES
('joao.silva@email.com', 'senha123', 'João Silva', '1990-05-10', '11987654321', '123e4567e89b12d3a456426614174000'),
('maria.oliveira@email.com', 'senha456', 'Maria Oliveira', '1985-08-22', '11912345678', '987e6543e21b32c7d654421324576000');

INSERT INTO roupa (nome, descricao, tamanho, tipo, preco, foto, codigoUsuario) 
VALUES
('Camiseta Masculina', 'Camiseta de algodão azul, confortável e estilosa', 'M', 'Camiseta', 49.90, NULL, 1),
('Vestido Floral', 'Vestido de verão com estampa floral, perfeito para o calor', 'G', 'Vestido', 79.90, NULL, 2);

